DROP DATABASE IF EXISTS openCV;
CREATE DATABASE IF NOT EXISTS opencv;
USE opencv;

DROP TABLE IF EXISTS opencv_users;
CREATE TABLE IF NOT EXISTS opencv_users (
	user_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	email VARCHAR(100) NOT NULL UNIQUE,
	salt VARCHAR(200) NOT NULL,
	pass VARCHAR(200) NOT NULL,
	screen_name VARCHAR(50) NOT NULL,
        activated INT NOT NULL
)ENGINE=InnoDB  DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1;

DROP TABLE IF EXISTS opencv_user_info;
CREATE TABLE IF NOT EXISTS opencv_user_info (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	user_id INT NOT NULL UNIQUE,
	name VARCHAR(25) NOT NULL,
	father_name VARCHAR(25) NOT NULL,
	mother_name VARCHAR(25) NOT NULL,
	present_address VARCHAR(250),
	parmanent_address VARCHAR(250) NOT NULL,
	gender VARCHAR(250) NOT NULL,
	marital_status VARCHAR(250) NOT NULL,
	religion int NOT NULL,
	blood_group VARCHAR(250) NOT NULL,
	cell VARCHAR(25) NOT NULL,
	cr_obj VARCHAR(500) NOT NULL,
	ref_1 VARCHAR(250) NOT NULL,
	ref_2 VARCHAR(250) NOT NULL
)ENGINE=InnoDB  DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1;

ALTER TABLE opencv_user_info
ADD CONSTRAINT FK_opencv_user_info FOREIGN KEY (user_id) REFERENCES opencv_users (user_id) ON DELETE CASCADE ON UPDATE CASCADE;


DROP TABLE IF EXISTS opencv_education;
CREATE TABLE IF NOT EXISTS opencv_education (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	user_id INT NOT NULL,
	degree VARCHAR(25) NOT NULL,
	exam_result DECIMAL(4,2) NOT NULL,
	institute_name VARCHAR(50) NOT NULL,
	passing_year INT NOT NULL
)ENGINE=InnoDB  DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1;

ALTER TABLE opencv_education
ADD CONSTRAINT FK_opencv_education FOREIGN KEY (user_id) REFERENCES opencv_users (user_id) ON DELETE CASCADE ON UPDATE CASCADE;


DROP TABLE IF EXISTS opencv_technical_skill;
CREATE TABLE IF NOT EXISTS opencv_technical_skill (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	user_id INT NOT NULL,
	name VARCHAR(50) NOT NULL,
	year_of_exp decimal(18,2) NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1;

ALTER TABLE opencv_technical_skill
ADD CONSTRAINT FK_opencv_technical_skill FOREIGN KEY (user_id) REFERENCES opencv_users (user_id) ON DELETE CASCADE ON UPDATE CASCADE;


DROP TABLE IF EXISTS opencv_image;
CREATE TABLE IF NOT EXISTS opencv_image (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	user_id INT NOT NULL UNIQUE,
	image_path VARCHAR(100)
) ENGINE=InnoDB  DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1;

ALTER TABLE opencv_image
ADD CONSTRAINT FK_opencv_image FOREIGN KEY (user_id) REFERENCES opencv_users (user_id) ON DELETE CASCADE ON UPDATE CASCADE;